name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
     name: build
     runs-on: ubuntu-latest
     steps:

     - name: Check out code
       uses: actions/checkout@v4

     - name: unit tests
       run: make build


  unit:
     name: unit
     runs-on: ubuntu-latest
     steps:

     - name: Check out code
       uses: actions/checkout@v4

     - name: unit tests
       run: make test
